In [52]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [54]:
df = pd.read_csv('Downloads/heartdisease.csv') 
df.head()

   age  Gender  Family  diet  Lifestyle  cholestrol  heartdisease
0    3       0       0     1          2           0             1
1    4       1       1     1          3           2             1
2    2       1       1     1          2           0             1
3    4       0       1     0          2           0             1
4    4       0       0     0          1           2             0

In [55]:
df.shape
df.isnull().sum()

age             0
Gender          0
Family          0
diet            0
Lifestyle       0
cholestrol      0
heartdisease    0
dtype: int64

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           12000 non-null  int64
 1   Gender        12000 non-null  int64
 2   Family        12000 non-null  int64
 3   diet          12000 non-null  int64
 4   Lifestyle     12000 non-null  int64
 5   cholestrol    12000 non-null  int64
 6   heartdisease  12000 non-null  int64
dtypes: int64(7)
memory usage: 656.4 KB

In [57]:
df.describe()

,age,Gender,Family,diet,Lifestyle,cholestrol,heartdisease
count,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,2.006417,0.503500,0.503583,0.488667,1.510750,1.002833,0.498417
std,1.422982,0.500009,0.500008,0.499892,1.113473,0.815811,0.500018
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
50%,2.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000
75%,3.000000,1.000000,1.000000,1.000000,3.000000,2.000000,1.000000
max,4.000000,1.000000,1.000000,1.000000,3.000000,2.000000,1.000000

In [58]:
df.columns

Index(['age', 'Gender', 'Family', 'diet', 'Lifestyle', 'cholestrol',
       'heartdisease'],
      dtype='object')

In [59]:
!pip install pgmpy==1.0.0 
import pgmpy
print(pgmpy.__version__)

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pgmpy==1.0.0 in c:\users\kamal\appdata\roaming\python\python313\site-packages (1.0.0)
Requirement already satisfied: networkx in c:\programdata\anaconda3\lib\site-packages (from pgmpy==1.0.0) (3.5)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from pgmpy==1.0.0) (2.3.5)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from pgmpy==1.0.0) (1.16.3)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (from pgmpy==1.0.0) (1.7.2)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (from pgmpy==1.0.0) (2.3.3)
Requirement already satisfied: torch in c:\users\kamal\appdata\roaming\python\python313\site-packages (from pgmpy==1.0.0) (2.13.0)
Requirement already satisfied: statsmodels in c:\programdata\anaconda3\lib\site-packages (from pgmpy==1.0.0) (0.14.5)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from pgmpy==1.0.0) (4.67.1)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (from pgmpy==1.0.0) (1.5.2)
Requirement already satisfied: opt-einsum in c:\programdata\anaconda3\lib\site-packages (from pgmpy==1.0.0) (3.4.0)
Requirement already satisfied: pyro-ppl in c:\users\kamal\appdata\roaming\python\python313\site-packages (from pgmpy==1.0.0) (1.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas->pgmpy==1.0.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas->pgmpy==1.0.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas->pgmpy==1.0.0) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->pgmpy==1.0.0) (1.17.0)
Requirement already satisfied: pyro-api>=0.1.1 in c:\users\kamal\appdata\roaming\python\python313\site-packages (from pyro-ppl->pgmpy==1.0.0) (0.1.2)
Requirement already satisfied: filelock in c:\programdata\anaconda3\lib\site-packages (from torch->pgmpy==1.0.0) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\programdata\anaconda3\lib\site-packages (from torch->pgmpy==1.0.0) (4.15.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\programdata\anaconda3\lib\site-packages (from torch->pgmpy==1.0.0) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\programdata\anaconda3\lib\site-packages (from torch->pgmpy==1.0.0) (1.14.0)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from torch->pgmpy==1.0.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\programdata\anaconda3\lib\site-packages (from torch->pgmpy==1.0.0) (2025.10.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy>=1.13.3->torch->pgmpy==1.0.0) (1.3.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm->pgmpy==1.0.0) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->torch->pgmpy==1.0.0) (3.0.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->pgmpy==1.0.0) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in c:\programdata\anaconda3\lib\site-packages (from statsmodels->pgmpy==1.0.0) (1.0.1)
Requirement already satisfied: packaging>=21.3 in c:\programdata\anaconda3\lib\site-packages (from statsmodels->pgmpy==1.0.0) (25.0)
1.0.0

In [63]:
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator 
model = DiscreteBayesianNetwork([ ('age', 'heartdisease'), ('Gender', 'heartdisease'), ('Family', 'heartdisease'), ('diet', 'heartdisease'), ('Lifestyle', 'heartdisease'), ('cholestrol', 'heartdisease') ])
mle = MaximumLikelihoodEstimator(model, df) 
cpds = mle.get_parameters()
model.add_cpds(*cpds)
print(model.get_cpds('heartdisease'))

INFO:pgmpy: Datatype (N=numerical, C=Categorical Unordered, O=Categorical Ordered) inferred from data:
 {'age': 'N', 'Gender': 'N', 'Family': 'N', 'diet': 'N', 'Lifestyle': 'N', 'cholestrol': 'N', 'heartdisease': 'N'}

+-----------------+---------------------+---------------+-----+---------------------+---------------------+
| Family          | Family(0)           | Family(0)     | ... | Family(1)           | Family(1)           |
+-----------------+---------------------+---------------+-----+---------------------+---------------------+
| Gender          | Gender(0)           | Gender(0)     | ... | Gender(1)           | Gender(1)           |
+-----------------+---------------------+---------------+-----+---------------------+---------------------+
| Lifestyle       | Lifestyle(0)        | Lifestyle(0)  | ... | Lifestyle(3)        | Lifestyle(3)        |
+-----------------+---------------------+---------------+-----+---------------------+---------------------+
| age             | age(0)              | age(0)        | ... | age(4)              | age(4)              |
+-----------------+---------------------+---------------+-----+---------------------+---------------------+
| cholestrol      | cholestrol(0)       | cholestrol(0) | ... | cholestrol(2)       | cholestrol(2)       |
+-----------------+---------------------+---------------+-----+---------------------+---------------------+
| diet            | diet(0)             | diet(1)       | ... | diet(0)             | diet(1)             |
+-----------------+---------------------+---------------+-----+---------------------+---------------------+
| heartdisease(0) | 0.9354838709677419  | 1.0           | ... | 0.02857142857142857 | 0.06666666666666667 |
+-----------------+---------------------+---------------+-----+---------------------+---------------------+
| heartdisease(1) | 0.06451612903225806 | 0.0           | ... | 0.9714285714285714  | 0.9333333333333333  |
+-----------------+---------------------+---------------+-----+---------------------+---------------------+

In [61]:
print(model.get_cpds('age'))

+--------+----------+
| age(0) | 0.20125  |
+--------+----------+
| age(1) | 0.200333 |
+--------+----------+
| age(2) | 0.19425  |
+--------+----------+
| age(3) | 0.199083 |
+--------+----------+
| age(4) | 0.205083 |
+--------+----------+

In [62]:
print(model.get_cpds('Gender'))

+-----------+--------+
| Gender(0) | 0.4965 |
+-----------+--------+
| Gender(1) | 0.5035 |
+-----------+--------+

In [51]:
print(model.get_cpds('Family'))

+-----------+----------+
| Family(0) | 0.496417 |
+-----------+----------+
| Family(1) | 0.503583 |
+-----------+----------+